"""Public agent-neutral service contracts."""

from ..cursor.service import (
    CursorTurnRequest,
    CursorTurnResult,
    StartJobRequest,
    TicketJobRequest,
    TicketStartOutcome,
    acknowledge_deliveries,
    acknowledge_delivery,
    acknowledge_quarantine_reservations,
    cancel_job,
    claim_delivery,
    count_jobs,
    cursor_turn,
    dismiss_announcement,
    job_status,
    list_jobs,
    list_quarantine_evidence,
    mark_delivered,
    nuke_jobs,
    pending_results,
    recover_jobs,
    release_deliveries,
    release_delivery,
    repeat_announcement,
    reply_job,
    resolve_manual_reconciliation,
    start_follow_up,
    start_job,
    start_jobs,
)

AgentTurnRequest = CursorTurnRequest
AgentTurnResult = CursorTurnResult
StartAgentJobRequest = StartJobRequest
agent_turn = cursor_turn

__all__ = [
    "AgentTurnRequest",
    "AgentTurnResult",
    "StartAgentJobRequest",
    "TicketJobRequest",
    "TicketStartOutcome",
    "acknowledge_deliveries",
    "acknowledge_delivery",
    "acknowledge_quarantine_reservations",
    "agent_turn",
    "cancel_job",
    "claim_delivery",
    "count_jobs",
    "dismiss_announcement",
    "job_status",
    "list_jobs",
    "list_quarantine_evidence",
    "mark_delivered",
    "nuke_jobs",
    "pending_results",
    "recover_jobs",
    "release_deliveries",
    "release_delivery",
    "repeat_announcement",
    "reply_job",
    "resolve_manual_reconciliation",
    "start_follow_up",
    "start_job",
    "start_jobs",
]
